// App
export const LOADING_STATE = 'LOADING_STATE';

// Agent
export const AGENT_PROFILE = 'AGENT_PROFILE';
export const AGENT_PROFILE_IS_LOADING = 'AGENT_PROFILE_IS_LOADING';
export const CLEAR_AGENT_PROFILE = 'CLEAR_AGENT_PROFILE';
export const AGENT_PROFILE_IS_UPDATING = 'AGENT_PROFILE_IS_UPDATING';
export const AGENT_LIVE_PROPERTIES = 'AGENT_LIVE_PROPERTIES';
export const AGENT_DRAFT_PROPERTIES = 'AGENT_DRAFT_PROPERTIES';
export const CLEAR_AGENT_LIVE_PROPERTIES = 'CLEAR_AGENT_LIVE_PROPERTIES';
export const CLEAR_AGENT_DRAFT_PROPERTIES = 'CLEAR_AGENT_DRAFT_PROPERTIES';
export const AGENT_LIVE_PROPERTIES_LOADING = 'AGENT_LIVE_PROPERTIES_LOADING';
export const AGENT_DRAFT_PROPERTIES_LOADING = 'AGENT_DRAFT_PROPERTIES_LOADING';
export const MOBILE_VERIFYING = 'MOBILE_VERIFYING'

// Music
export const MUSIC_LOADING = 'MUSIC_LOADING'
export const MUSIC_FILES = 'MUSIC_FILES'
export const MUSIC_TRENDING = 'MUSIC_TRENDING'

// Property
export const HANDLE_ADD_PROPERTY = 'HANDLE_ADD_PROPERTY';
export const ALL_PROPERTIES = 'ALL_PROPERTIES';
export const ALL_PROPERTIES_LOADING = 'ALL_PROPERTIES_LOADING';
export const ALL_PROPERTIES_ERROR = 'ALL_PROPERTIES_ERROR';
export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const SET_CURRENT_PROPERTY = 'SET_CURRENT_PROPERTY';
export const CLEAR_NEW_PROPERTY = 'CLEAR_NEW_PROPERTY';
export const SET_INSPECTION_TIME = 'SET_INSPECTION_TIME';
export const SET_AUCTION_DATE = 'SET_AUCTION_DATE';
export const PROPERTY_SEARCH_RESULTS = 'PROPERTY_SEARCH_RESULTS';
export const PROPERTY_SEARCH_IS_LOADING = 'PROPERTY_SEARCH_IS_LOADING';
export const CLEAR_PROPERTY_SEARCH_RESULTS = 'CLEAR_PROPERTY_SEARCH_RESULTS';
export const PROPERTY_SEARCH_FILTERS = 'PROPERTY_SEARCH_FILTERS';
export const SET_HASHTAGS = 'SET_HASHTAGS';
export const SET_TRENDINGPROPERTIES = 'SET_TRENDINGPROPERTIES'
export const MUSIC_COUNT = 'MUSIC_COUNT'

// Auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_TOKEN_UPDATED = 'AUTH_TOKEN_UPDATED';
export const USER_LOADED = 'USER_LOADED';
export const PROFILE_LOADING = 'USER_LOADING';
export const PROFILE_IS_UPDATING = 'PROFILE_IS_UPDATING';
export const USER_PROFILE = 'USER_PROFILE';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOOADING';
export const RESET_PASSWORD_SUBMITTED = 'RESET_PASSWORD_SUBMITTED';

// Follows
export const ALL_FOLLOWERS = 'ALL_FOLLOWERS';
export const FOLLOWERS_IS_LOADING = 'FOLLOWERS_IS_LOADING';
export const ALL_FOLLOWING = 'ALL_FOLLOWING';
export const FOLLOWING_IS_LOADING = 'FOLLOWING_IS_LOADING';
export const FOLLOWING_COUNT = 'FOLLOWING_COUNT';
export const FOLLOWERS_COUNT = 'FOLLOWERS_COUNT';
export const ALL_FOLLOWING_LOADED = 'ALL_FOLLOWING_LOADED';
export const ALL_FOLLOWERS_LOADED = 'ALL_FOLLOWERS_LOADED';

// Likes
export const LIKED_PROPERTIES = 'LIKED_PROPERTIES';
export const CLEAR_LIKED_PROPERTIES = 'CLEAR_LIKED_PROPERTIES';
export const LIKED_PROPERTIES_COUNT = 'LIKED_PROPERTIES_COUNT';
export const LIKED_PROPERTIES_IS_LOADING = 'LIKED_PROPERTIES_IS_LOADING';

// Messages
export const ALL_CONVERSATIONS = 'ALL_CONVERSATIONS';
export const CONVERSATIONS_LOADING = 'CONVERSATIONS_LOADING';
export const MESSAGES_IN_CONVERSATION = 'MESSAGES_IN_CONVERSATION';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const CURRENT_CONVERSATION = 'CURRENT_CONVERSATION';
export const MESSAGES_IS_LOADING = 'MESSAGES_IS_LOADING';
export const MESSAGE_IS_SENDING = 'MESSAGE_IS_SENDING';
export const AE = 'AE';
