export default [
  { name: 'Aspire.mp3' },
  { name: 'Beyond_Dreams.mp3' },
  { name: 'Big_Apple.mp3' },
  { name: 'Clear_Progress.mp3' },
  { name: 'Driven_to_Success.mp3' },
  { name: 'Epic_Cinematic.mp3' },
  { name: 'Follow_your_Dreams.mp3' },
  { name: 'Hopeful_Journey.mp3' },
  { name: 'Hotshot.mp3' },
  { name: 'Inspirational_Outlook.mp3' },
  { name: 'Little_Idea.mp3' },
  { name: 'Make_your_Dreams_Reality.mp3' },
  { name: 'Motivational.mp3' },
  { name: 'Reach_for_Success.mp3' },
  { name: 'Shine_Bright.mp3' },
  { name: 'Stomps_and_Claps.mp3' },
  { name: 'Storybook.mp3' },
  { name: 'Teamwork.mp3' },
  { name: 'Think_BIG.mp3' },
  { name: 'Upbeat_Party.mp3' },
  { name: 'We_Made_It.mp3' },
];
